Fix Idea Plugin ClassCastException - CreateIndex and CreateView (#5772)
* Fix Idea Plugin ClassCastException - CreateIndex and CreateView

 CreateIndex and CreateView

java.lang.ClassCastException: Don't use #getElementType method. It is deprecated.
Implement and use #getIElementType

* Update CHANGELOG.md