Increase timeout in MappingJvmTest
Likely due to JVM warmup time and compilation on lambda - timeout needs increasing

org.junit.runners.model.TestTimedOutException: test timed out after 1 seconds
at app.cash.sqldelight.coroutines.FlowQuery.toFlow(FlowExtensions.kt:37)
at app.cash.sqldelight.coroutines.MappingJvmTest$mapToOneNonNullUsesContext$1.invokeSuspend(MappingJvmTest.kt:60)
•••
at app.cash.sqldelight.coroutines.RunTestKt$runTest$1.invokeSuspend(RunTest.kt:24)
•••
at app.cash.sqldelight.coroutines.RunTestKt.runTest(RunTest.kt:21)
at app.cash.sqldelight.coroutines.MappingJvmTest.mapToOneNonNullUsesContext(MappingJvmTest.kt:58)